routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        $data['page_slug'] = request()->route()->uri();
        return view('crm.dashboard', $data);
    })->name('dashboard');

    Route::group(['middlerware' => 'role:Admin'], function() {

        Route::resource('/plot', 'PlotController');
        Route::resource('/client', 'ClientController');
        Route::resource('/agent', 'AgentController');
        Route::resource('/manager', 'ManagerController');
        Route::resource('/employee', 'EmployeeController');
        Route::resource('/housing', 'HousingSchemeController');

        // For Customer Assigned to Housing Scheme
        Route::post('/scheme', 'LocationController@scheme')->name('store.scheme');


        //For locations of schemes
        Route::get('/location', 'LocationController@index')->name('get.location');
        Route::get('/createlocation', 'LocationController@create')->name('create.location');
        Route::post('/storelocation', 'LocationController@store')->name('store.location');
        Route::get('/editlocation/{id}', 'LocationController@edit')->name('edit.location');
        Route::post('/updatelocation', 'LocationController@update')->name('update.location');
        Route::get('/deletelocation/{id}', 'LocationController@destroy')->name('delete.location');

        //For Sales Agreement
        Route::get('/sales', 'SaleController@index')->name('get.sale');
        Route::get('/listsales', 'SaleController@getSales')->name('list.sale');
        Route::get('/salescustomer/{id}', 'SaleController@customerData')->name('sale.customerData');
        Route::get('/salesagent/{id}', 'SaleController@agentData')->name('sale.agentData');
        Route::get('/salesplot/{id}', 'SaleController@plotData')->name('sale.plotData');
        Route::get('/viewsales/{id}', 'SaleController@viewSales')->name('view.sale');
        Route::post('/savesales', 'SaleController@saveSales')->name('save.sale');

        // For Installment View
        Route::get('/installmentpay/{id}', 'SaleController@installment')->name('installment.pay');

        // For Cash Installment
        Route::post('/cashinstallment/{id}', 'SaleController@cashinstallment')->name('installment.cash');
        Route::post('/cashuninstallment/{id}', 'SaleController@cashuninstallment')->name('uninstallment.cash');

        // For Monthly Installment
        Route::post('/monthlyinstallment/{id}', 'SaleController@monthlyinstallment')->name('installment.monthly');
        Route::post('/monthlyuninstallment/{id}', 'SaleController@monthlyuninstallment')->name('uninstallment.monthly');

        // For Sale Delete
        Route::get('/delete/{id}', 'SaleController@deletesale')->name('sale.delete');

        Route::get('/download', 'EmpController@download')->name('download');
    });

});


require __DIR__.'/auth.php';

app/Models/Agent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function cnic(){
        return $this->hasMany(AgentCnic::class, 'user_id' , 'id');

    }

}

app/Http/Controllers/AgentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Agent;
use App\Models\AgentCnic;
use Illuminate\Http\Request;

class AgentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['page_slug'] = request()->route()->uri();
        $data['agent'] = Agent::where('status','yes')->get();
        // dd($data['agent']);
        return view('crm.agent.agent', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['page_slug'] = request()->route()->uri();
        return view('crm.agent.create-agent', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->toArray());
        $image_path = $request->file('profile')->store('images/agents/profile', 'public');
        $profile_image = $image_path;
        $agent = Agent::create([
            'profile' => $profile_image,
            'reg_number' => $request->reg_number,
            'name' => $request->name,
            'father_name' => $request->father_name,
            'data_of_birth' => $request->date_of_birth,
            'gender' => $request->gender,
            'comission' => $request->commission,
            'cnic_no' => $request->agentcnic_no,
            'cell_no' => $request->cell,
            'phone_no' => $request->phone,
            'email' => $request->email,
            'address' => $request->address,
            'city' => $request->city,
            'status' => $request->status,
            'created_by' => auth()->user()->id,

        ]);

        $agent_images = $request->agentcnic;
        foreach ($agent_images as $cnic_images) {
            $image_path = $cnic_images->store('images/agents/cnic', 'public');
            $pictures = $image_path;
            $agent_images = AgentCnic::create([
                'user_id' => $agent->id,
                'images' => $pictures,
            ]);
        }

        if ($agent_images->id) {
            return redirect('/agent')->with(['success' => 'Agent is successfully added']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Agent  $agent
     * @return \Illuminate\Http\Response
     */
    public function show(Agent $agent)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Agent  $agent
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['page_slug'] = 'agent';
        $data['agent'] = Agent::find($id);
        return view('crm.agent.update-agent', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Agent  $agent
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agent $agent)
    {
        if ($request->hasFile('profile')) {
            $image_path = $request->file('profile')->store('images/agents/profile', 'public');
            $profile = $image_path;
            $agent = Agent::updateOrCreate(
                ['id' => $request->id],
                [
                    'profile' => $profile,
                    'reg_number' => $request->reg_number,
                    'name' => $request->name,
                    'father_name' => $request->father_name,
                    'data_of_birth' => $request->date_of_birth,
                    'gender' => $request->gender,
                    'cnic_no' => $request->agentcnic_no,
                    'comission' => $request->commission,
                    'cell_no' => $request->cell,
                    'phone_no' => $request->phone,
                    'email' => $request->email,
                    'address' => $request->address,
                    'city' => $request->city,
                    'status' => $request->status,
                    'created_by' => auth()->user()->id,
                ]
            );
        } else {
            $agent = Agent::updateOrCreate(
                ['id' => $request->id],
                [
                    'reg_number' => $request->reg_number,
                    'name' => $request->name,
                    'father_name' => $request->father_name,
                    'data_of_birth' => $request->date_of_birth,
                    'gender' => $request->gender,
                    'comission' => $request->commission,
                    'cnic_no' => $request->agentcnic_no,
                    'cell_no' => $request->cell,
                    'phone_no' => $request->phone,
                    'email' => $request->email,
                    'address' => $request->address,
                    'city' => $request->city,
                    'status' => $request->status,
                    'created_by' => auth()->user()->id,
                ]
            );
        }

        $agent = Agent::find($request->id);
        $agent_images = $request->agentcnic;
        if ($request->hasFile('agentcnic')) {
            AgentCnic::where('user_id', $request->id)->delete();
            foreach ($agent_images as $agent_img) {
                $image_path = $agent_img->store('images/agents/cnic', 'public');
                $pictures = $image_path;
                $agent_images = AgentCnic::create([
                    'user_id' => $request->id,
                    'images' => $pictures
                ]);
            }
        }

        return redirect('/agent')->with(['update' => 'Agent is successfully updated']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Agent  $agent
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        // dd($id);
        $agent = Agent::find($id)->update(['status' => 'no']);
        if($agent){
            return redirect('/agent')->with(['delete' => 'Agent is delete successfully']);
        }
    }
}

resources/views/crm/agent/agent.blade.php
@extends('crm.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">Agent Detials
        </div>
        <div class="card-toolbar">
            <!--begin::Button-->
            <a href="{{ route('agent.create') }}" class="btn btn-primary font-weight-bolder">
                <span class="svg-icon svg-icon-md">
                    <i class="fa fa-plus-circle"></i>
                </span>New Record</a>
            <!--end::Button-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Search Form-->
        <!--begin::Search Form-->
        <div class="mb-7">
            <div class="row align-items-center">
                <div class="col-lg-3">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="input-icon">
                                <input type="text" class="form-control" placeholder="Search..."
                                    id="kt_datatable_search_query" />
                                <span>
                                    <i class="flaticon2-search-1 text-muted"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-xl-4 mt-5 mt-lg-0">
                    <a href="#" class="btn btn-light-primary px-6 font-weight-bold">Search</a>
                </div>
            </div>
        </div>
        <!--end::Search Form-->
        <!--end: Search Form-->
        <!--begin: Datatable-->
        <div class="panel panel-default">
            @if (session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
            @elseif (session('delete'))
                <div class="alert alert-danger">{{ session('delete') }}</div>
            @elseif (session('update'))
                <div class="alert alert-success">{{ session('update') }}</div>
            @endif
        </div>
        <table class="datatable datatable-bordered datatable-head-custom" id="kt_datatable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Profile</th>
                    <th>Reg #</th>
                    <th>Name</th>
                    <th>Contact</th>
                    <th>Address</th>
                    <th>Active</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php $x=0 ?>
                @foreach ($agent as $data)
                    {{-- @dd($data->reg_number) --}}
                    <tr>
                    <td>{{$x+1}}</td>
                    <td><img src="{{asset('storage/'.$data->profile)}}" height="80px" width="80px"></td>
                    <td>{{ $data->reg_number }}</td>
                    <td>{{$data->name}}</td>
                    <td>{{$data->cell_no}}</td>
                    <td>{{ $data->address}}</td>
                    <td>{{ $data->status}}</td>
                    <td data-field="Actions" data-autohide-disabled="false" aria-label="null" class="datatable-cell">
                        <span style="overflow: visible; position: relative; width: 125px;">
                            <a href="{{route('agent.edit', $data->id)}}" class="btn btn-sm btn-clean btn-icon mr-2" title="Edit details">
                                <span class="svg-icon svg-icon-md">
                                    <i class="fas fa-pen"></i>
                                </span>
                            </a>
                            <form method="Post" action="{{ route('agent.destroy',$data->id) }}" style="display: -webkit-inline-box;">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-clean btn-icon" title="Delete">
                                    <span class="svg-icon svg-icon-md">
                                        <i class="fas fa-trash"></i>
                                    </span>
                                </button>
                            </form>
                        </span>
                    </td>
                </tr>
                <?php $x++; ?>
                @endforeach
            </tbody>
        </table>
        <!--end: Datatable-->
    </div>
</div>
@endsection

resources/views/crm/agent/create-agent.blade.php
@extends('crm.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            New Agent
        </h3>
    </div>
    <!--begin::Form-->
    <form method="POST" action="{{route('agent.store')}}" enctype="multipart/form-data" class="form">
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <div class="col-lg-12">
                    <h6>Profile Picture: <span class="text-danger font-weight-bolder font-size-lg">*</span></h6>
                    <div class="image-input image-input-outline" id="kt_image_4"
                        style="background-image: url({{ asset('crm/assets/media/users/blank.png') }}) ">

                        <div class="image-input-wrapper"
                            style="background-image: url({{ asset('crm/assets/media/users/100_1.jpg') }}) "></div>

                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                            data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                            <i class="fa fa-pen icon-sm text-muted"></i>
                            <input type="file" name="profile" accept=".png, .jpg, .jpeg" required/>
                            <input type="hidden" name="profile_avatar_remove" />
                        </label>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                            data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                            <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow"
                            data-action="remove" data-toggle="tooltip" title="Remove avatar">
                            <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Reg Number:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <input type="number" name="reg_number" class="form-control"
                        placeholder="Enter reg number" required/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Name:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <input type="text" name="name" class="form-control"
                        placeholder="Enter name" required/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Father Name:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <input type="text" name="father_name" class="form-control"
                        placeholder="Enter father name" required/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Date of Birth:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <input type="date" name="date_of_birth" class="form-control"
                        placeholder="Enter father name" required/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Gender:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <select type="date" name="gender" class="form-control" required>
                        <option value="">Please Select Gender</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Commission Ratio:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <input type="number" placeholder="Enter Comission Ratio" step="0.001" name="commission" class="form-control" required="" required/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>C.N.I.C No:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <input type="text" data-inputmask="'mask': '99999-9999999-9'" placeholder="XXXXX-XXXXXXX-X"
                        name="agentcnic_no" class="form-control agentcnic " required/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>C.N.I.C Picture:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <input type="file" class="dropify" data-height="200" data-allowed-file-extensions="png jpg jpeg" name="agentcnic[]"
                        data-errors-position="outside" data-max-file-size-preview="2M" data-show-errors="true" multiple required/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Cell No:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <input type="tel" name="cell" class="form-control"
                        placeholder="Enter full cell nnumber" required />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Phone No:</label>
                    <input type="tel" name="phone" class="form-control"
                        placeholder="Enter full phone number" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Email<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <input type="email" name="email" class="form-control"
                        placeholder="Enter full phone number" required />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Address:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="address" placeholder="Enter address" required/>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>City:</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="city" placeholder="Enter city" />
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Status:<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                    <select type="date" name="status" class="form-control" required>
                        <option value="">Please Select Status</option>
                        <option value="yes">Yes</option>
                        <option value="no">No</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row text-center">
                <div class="col-lg-2">
                    <button type="submit" class="btn btn-primary btn-lg btn-block btn-check">Save</button>
                </div>
            </div>
        </div>
    </form>
</div>

@endsection
@section('footer.script')
<script>
    var avatar4 = new KTImageInput('kt_image_4');

    avatar4.on('cancel', function (imageInput) {
        swal.fire({
            title: 'Image successfully changed !',
            type: 'success',
            buttonsStyling: false,
            confirmButtonText: 'Awesome!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

    avatar4.on('change', function (imageInput) {
        swal.fire({
            title: 'Image successfully changed !',
            type: 'success',
            buttonsStyling: false,
            confirmButtonText: 'Awesome!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

    avatar4.on('remove', function (imageInput) {
        swal.fire({
            title: 'Image successfully removed !',
            type: 'error',
            buttonsStyling: false,
            confirmButtonText: 'Got it!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

    $('.agentcnic').change('change', function () {
        // var idToTest = '12345-1234567-1',
        var checkcinic = $('.agentcnic').val();
        myRegExp = new RegExp(/\d{5}-\d{7}-\d/);

        if (myRegExp.test(checkcinic)) {
            $('.btn-check').removeAttr('disabled');
            $('.agentcnic').removeClass('is-invalid');
        } else {
            $('.agentcnic').addClass('is-invalid');
            $('.btn-check').attr('disabled', 'disabled');
        }
    });

</script>
@endsection