routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        $data['page_slug'] = request()->route()->uri();
        return view('crm.dashboard', $data);
    })->name('dashboard');

    Route::group(['middlerware' => 'role:Admin'], function() {

        Route::resource('/plot', 'PlotController');
        Route::resource('/client', 'ClientController');
        Route::resource('/agent', 'AgentController');
        Route::resource('/manager', 'ManagerController');
        Route::resource('/employee', 'EmployeeController');
        Route::resource('/housing', 'HousingSchemeController');

        // For Customer Assigned to Housing Scheme
        Route::post('/scheme', 'LocationController@scheme')->name('store.scheme');


        //For locations of schemes
        Route::get('/location', 'LocationController@index')->name('get.location');
        Route::get('/createlocation', 'LocationController@create')->name('create.location');
        Route::post('/storelocation', 'LocationController@store')->name('store.location');
        Route::get('/editlocation/{id}', 'LocationController@edit')->name('edit.location');
        Route::post('/updatelocation', 'LocationController@update')->name('update.location');
        Route::get('/deletelocation/{id}', 'LocationController@destroy')->name('delete.location');

        //For Sales Agreement
        Route::get('/sales', 'SaleController@index')->name('get.sale');
        Route::get('/listsales', 'SaleController@getSales')->name('list.sale');
        Route::get('/salescustomer/{id}', 'SaleController@customerData')->name('sale.customerData');
        Route::get('/salesagent/{id}', 'SaleController@agentData')->name('sale.agentData');
        Route::get('/salesplot/{id}', 'SaleController@plotData')->name('sale.plotData');
        Route::get('/viewsales/{id}', 'SaleController@viewSales')->name('view.sale');
        Route::post('/savesales', 'SaleController@saveSales')->name('save.sale');

        // For Installment View
        Route::get('/installmentpay/{id}', 'SaleController@installment')->name('installment.pay');

        // For Cash Installment
        Route::post('/cashinstallment/{id}', 'SaleController@cashinstallment')->name('installment.cash');
        Route::post('/cashuninstallment/{id}', 'SaleController@cashuninstallment')->name('uninstallment.cash');

        // For Monthly Installment
        Route::post('/monthlyinstallment/{id}', 'SaleController@monthlyinstallment')->name('installment.monthly');
        Route::post('/monthlyuninstallment/{id}', 'SaleController@monthlyuninstallment')->name('uninstallment.monthly');

        // For Sale Delete
        Route::get('/delete/{id}', 'SaleController@deletesale')->name('sale.delete');

        Route::get('/download', 'EmpController@download')->name('download');
    });

});


require __DIR__.'/auth.php';

resources/views/crm/housing/create-housing.blade.php
@extends('crm.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            New Housing Scheme
        </h3>
    </div>
    <div class="panel panel-default">
        @if (session('status'))
            <div class="alert alert-success">{{ session('status') }}</div>
        @endif
    </div>
    <!--begin::Form-->
    <form action="{{ route('housing.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <label class="col-2 col-form-label">Name<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="text" name="name" id="example-text-input" placeholder="Enter the name" required/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label">Manager<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <select class="form-control select2" name="managers[]" id="managerSelect" multiple="multiple" required>
                        @foreach ($manager as $data)
                            <option value="{{ $data->id }}">{{$data->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label">Employee<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <select class="form-control select2" name="employees[]" id="employeeSelect" multiple="multiple" required>
                        @foreach ($employee as $data)
                            <option value="{{ $data->id }}">{{$data->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Phone No.<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="tel" name="phone" id="example-text-input" placeholder="Enter the contact number" required/>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Email<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="email" name="email" id="example-text-input" placeholder="Enter the email" required/>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Address<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="text" name="address" id="example-text-input" placeholder="Enter the address" required/>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Website Link<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="text" name="website" id="example-text-input" placeholder="Enter the website link" required/>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Logo<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input type="file" class="dropify" data-height="200" data-allowed-file-extensions="png jpg jpeg" data-errors-position="outside" name="logo"  data-max-file-size-preview="2M"  data-show-errors="true" required/>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-2">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Save</button>
                </div>
                <div class="col-10">
                </div>
            </div>
        </div>
    </form>
</div>
@endsection
@section('footer.script')
<script>
    $(document).ready(function() {
            $('#managerSelect').select2({
                placeholder: "Select Managers",
                allowClear: true
            });

            $('#employeeSelect').select2({
                placeholder: "Select Employees",
                allowClear: true
            });
        });
</script>
@endsection

resources/views/crm/housing/housing.blade.php
@extends('crm.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">Housing Scheme</h3>
        </div>
        <div class="card-toolbar">
            <!--begin::Button-->
            <a href="{{ route('housing.create') }}" class="btn btn-primary font-weight-bolder">
                <span class="svg-icon svg-icon-md">
                    <i class="fa fa-plus-circle"></i>
                </span>New Record</a>
            <!--end::Button-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Search Form-->
        <!--begin::Search Form-->
        <div class="mb-7">
            <div class="row align-items-center">
                <div class="col-lg-3">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="input-icon">
                                <input type="text" class="form-control" placeholder="Search..."
                                    id="kt_datatable_search_query" />
                                <span>
                                    <i class="flaticon2-search-1 text-muted"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-xl-4 mt-5 mt-lg-0">
                    <a href="#" class="btn btn-light-primary px-6 font-weight-bold">Search</a>
                </div>
            </div>
        </div>
        <!--end::Search Form-->
        <!--end: Search Form-->
        <!--begin: Datatable-->
        <div class="panel panel-default">
            @if (session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
            @elseif (session('delete'))
                <div class="alert alert-danger">{{ session('delete') }}</div>
            @elseif (session('update'))
                <div class="alert alert-success">{{ session('update') }}</div>
            @endif
        </div>
        <br>
        <table class="datatable datatable-bordered datatable-head-custom" id="kt_datatable">
            <thead>
                <tr>
                    <th >#</th>
                    <th>Logo</th>
                    <th>Name</th>
                    <th>Manager</th>
                    <th>Employee</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php $x = 0  ?>
                @foreach ($housing as $data)
                <tr>
                    <td >{{$x+1}}</td>
                    <td><img src="{{ asset('storage/'.optional($data)->logo) }}" height="80px" width="80px" /></td>
                    <td>{{$data->name}}</td>
                    <td>
                        @foreach ($data->manager as $managerusers)
                        {{$managerusers->name.','}}
                        @endforeach
                    </td>
                    <td>
                        @foreach ($data->employee as $employeeusers)
                        {{$employeeusers->name.','}}
                        @endforeach
                    </td>
                    <td class="text-right">{{$data->address}}</td>
                    <td class="text-right">{{$data->number}}</td>
                    <td data-field="Actions" data-autohide-disabled="false" aria-label="null" class="datatable-cell">
                        <span style="overflow: visible; position: relative; width: 125px;">
                        <a href="{{ route('housing.edit',$data->id) }}" class="btn btn-sm btn-clean btn-icon mr-2" title="Edit details">
                                <span class="svg-icon svg-icon-md">
                                    <i class="fas fa-pen"></i>
                                </span>
                            </a>
                            <form method="Post" action="{{ route('housing.destroy',$data->id) }}" style="display: -webkit-inline-box;">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-clean btn-icon" title="Delete">
                                    <span class="svg-icon svg-icon-md">
                                        <i class="fas fa-trash"></i>
                                    </span>
                                </button>
                            </form>
                        </span>
                    </td>
                </tr>
                <?php $x++;?>
                @endforeach
            </tbody>
        </table>
        <!--end: Datatable-->
    </div>
</div>
@endsection

resources/views/crm/housing/update-housing.blade.php
@extends('crm.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            Update Housing Scheme
        </h3>
    </div>
    <!--begin::Form-->
    <form action="{{ route('housing.update', $housing->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <div class="card-body">
            <div class="form-group row">
                <label class="col-2 col-form-label">Name<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="hidden" name="id" id="example-text-input" value="{{$housing->id}}"/>
                    <input class="form-control" type="text" name="name" id="example-text-input" value="{{$housing->name}}" required/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2 col-form-label">Manager<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <select class="form-control select2" name="manager[]" id="managerSelect" multiple required>
                        @foreach ($manager as $key => $data)
                            @if (isset($housing->manager[$key]))
                                <option value="{{ $data->id }}" {{ ($data->id == $housing->manager[$key]->id) ? 'selected' : null  }}>{{ $data->name }}</option>
                            @else
                                <option value="{{ $data->id }}">{{ $data->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-2 col-form-label">Employee<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <select class="form-control select2" name="employee[]" id="employeeSelect" multiple required>
                        @foreach ($employee as $key => $data)
                            @if (isset($housing->employee[$key]))
                                <option value="{{ $data->id }}" {{ ($data->id == $housing->employee[$key]->id) ? 'selected' : null  }}>{{ $data->name }}</option>
                            @else
                                <option value="{{ $data->id }}">{{ $data->name }}</option>
                            @endif
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Phone No.<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="tel" name="phone" id="example-text-input" value="{{$housing->number}}" required/>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Email<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="email" name="email" id="example-text-input" placeholder="Enter the email" value="{{$housing->email}}" required/>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Address<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="address" name="address" id="example-text-input" value="{{$housing->address}}" required/>
                </div>
            </div>
            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Website Link<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input class="form-control" type="text" name="website" id="example-text-input" placeholder="Enter the website link" value="{{$housing->website}}" required/>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Logo<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                <div class="col-10">
                    <input type="file" class="dropify" data-height="200" data-default-file="{{ asset('storage/'.optional($housing)->logo) }}" data-allowed-file-extensions="pdf png psd" data-errors-position="outside" name="logo"  data-max-file-size-preview="2M"  data-show-errors="true"/>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-2">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Update</button>
                </div>
                <div class="col-10">
                </div>
            </div>
        </div>
    </form>
</div>
@endsection
@section('footer.script')
<script>
    $(document).ready(function() {
            $('#managerSelect').select2({
                placeholder: "Select Managers",
                allowClear: true
            });

            $('#employeeSelect').select2({
                placeholder: "Select Employees",
                allowClear: true
            });
        });
</script>
@endsection