routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('auth.login');
});

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        $data['page_slug'] = request()->route()->uri();
        return view('crm.dashboard', $data);
    })->name('dashboard');

    Route::group(['middlerware' => 'role:Admin'], function() {

        Route::resource('/plot', 'PlotController');
        Route::resource('/client', 'ClientController');
        Route::resource('/agent', 'AgentController');
        Route::resource('/manager', 'ManagerController');
        Route::resource('/employee', 'EmployeeController');
        Route::resource('/housing', 'HousingSchemeController');

        // For Customer Assigned to Housing Scheme
        Route::post('/scheme', 'LocationController@scheme')->name('store.scheme');


        //For locations of schemes
        Route::get('/location', 'LocationController@index')->name('get.location');
        Route::get('/createlocation', 'LocationController@create')->name('create.location');
        Route::post('/storelocation', 'LocationController@store')->name('store.location');
        Route::get('/editlocation/{id}', 'LocationController@edit')->name('edit.location');
        Route::post('/updatelocation', 'LocationController@update')->name('update.location');
        Route::get('/deletelocation/{id}', 'LocationController@destroy')->name('delete.location');

        //For Sales Agreement
        Route::get('/sales', 'SaleController@index')->name('get.sale');
        Route::get('/listsales', 'SaleController@getSales')->name('list.sale');
        Route::get('/salescustomer/{id}', 'SaleController@customerData')->name('sale.customerData');
        Route::get('/salesagent/{id}', 'SaleController@agentData')->name('sale.agentData');
        Route::get('/salesplot/{id}', 'SaleController@plotData')->name('sale.plotData');
        Route::get('/viewsales/{id}', 'SaleController@viewSales')->name('view.sale');
        Route::post('/savesales', 'SaleController@saveSales')->name('save.sale');

        // For Installment View
        Route::get('/installmentpay/{id}', 'SaleController@installment')->name('installment.pay');

        // For Cash Installment
        Route::post('/cashinstallment/{id}', 'SaleController@cashinstallment')->name('installment.cash');
        Route::post('/cashuninstallment/{id}', 'SaleController@cashuninstallment')->name('uninstallment.cash');

        // For Monthly Installment
        Route::post('/monthlyinstallment/{id}', 'SaleController@monthlyinstallment')->name('installment.monthly');
        Route::post('/monthlyuninstallment/{id}', 'SaleController@monthlyuninstallment')->name('uninstallment.monthly');

        // For Sale Delete
        Route::get('/delete/{id}', 'SaleController@deletesale')->name('sale.delete');

        Route::get('/download', 'EmpController@download')->name('download');
    });

});


require __DIR__.'/auth.php';

app/Models/Plot.php
<?php

namespace App\Models;

use App\Models\PlotImage;
use App\Models\HousingScheme;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Plot extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function housing(){
        return $this->belongsTo(HousingScheme::class,'housing_scheme_id' , 'id');
    }

    public function images(){
        return $this->hasMany(PlotImage::class,'plot_id' , 'id' );
    }
}

app/Http/Controllers/PlotController.php
<?php

namespace App\Http\Controllers;

use App\Models\Plot;
use App\Models\Location;
use App\Models\PlotImage;
use Illuminate\Http\Request;
use App\Models\HousingScheme;
use Illuminate\Support\Facades\Auth;

class PlotController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $current_user = Auth::user();
        $data['page_slug'] = request()->route()->uri();
        $data['plot_detials'] = Plot::with('housing.manager')->when( ( $current_user->hasRole('admin') ) ,function ($query) use ($current_user) {})
        ->when( ( $current_user->hasRole('manager') ) ,function ($query) use ($current_user) {
            $query->whereHas('housing.manager', function ($query) use ($current_user) {
                $query->where(['manager_id' => auth()->user()->manager->manager_id]);
            });})
        ->when( ( $current_user->hasRole('employee') ) ,function ($query) use ($current_user) {
            $query->whereHas('housing.employee', function ($query) use ($current_user) {
                $query->where(['employee_id' => auth()->user()->employee->employee_id]);
            });
        })->get();
        return view('crm.plot.plot', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $current_user = Auth::user();
        $data['page_slug'] = request()->route()->uri();
        $data['plot'] = HousingScheme::with('location')->when( ( $current_user->hasRole('admin') ) ,function ($query) use ($current_user) {})
        ->when( ( $current_user->hasRole('manager') ) ,function ($query) use ($current_user) {
            $query->whereHas('manager', function ($query) use ($current_user) {
                $query->where(['scheme_id' => auth()->user()->manager->scheme_id]);
            });
        })->where('delete_at','0')->get();
        return view('crm.plot.create-plot', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        $plot = Plot::create([
            'plot_id' => $request->plot_id,
            'housing_scheme_id' => $request->housingscheme_id,
            'type' => $request->type,
            'block' => $request->block,
            'phase' => $request->phase,
            'width' => $request->width,
            'length' => $request->length,
            'sqrft' => $request->sqrft,
            'sqrmt' => $request->sqrmt,
            'marla' => $request->marla,
            'cost' => $request->cost,
            'totalcost' => $request->cost,
            'khewat_no' => $request->khewat_no,
            'khasra_no' => $request->khasra_no,
            'status' => $request->status,
            'location' => $request->location,
            'address' => $request->address,
            'create_by' => auth()->user()->id,

        ]);

        $plot_images = $request->plotpictures;
        if($plot_images){
            foreach ($plot_images as $plot_images) {
                $image_path = $plot_images->store('images/plot', 'public');
                $pictures = $image_path;
                $plot_images = PlotImage::create([
                    'plot_id' => $plot->id,
                    'pictures' => $pictures,
                ]);
            }
        }


        if ($plot) {
            return redirect('/plot')->with(['success' => 'Plot is successfully added']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Plot  $plot
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['page_slug'] = 'plot';
        $data['plot'] = Plot::with('housing')->find($id);
        // dd($data['plot']);
        return view('crm.plot.view-plot', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Plot  $plot
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $current_user = Auth::user();
        $data['page_slug'] = 'plot';
        $data['housing'] = HousingScheme::with('location')->when( ( $current_user->hasRole('admin') ) ,function ($query) use ($current_user) {})
        ->when( ( $current_user->hasRole('manager') ) ,function ($query) use ($current_user) {
            $query->whereHas('manager', function ($query) use ($current_user) {
                $query->where(['scheme_id' => auth()->user()->manager->scheme_id]);
            });
        })->where('delete_at','0')->get();
        $data['plot'] = Plot::find($id);
        return view('crm.plot.update-plot', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Plot  $plot
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        // dd($request->toArray());
        $plot = Plot::find($request->id);
        $plot_images = $request->plotpictures;
        if ($request->hasFile('plotpictures')) {
            PlotImage::where('plot_id', $request->id)->delete();
            foreach ($plot_images as $plot_img) {
                $image_path = $plot_img->store('images/plot', 'public');
                $pictures = $image_path;
                // dump($pictures);
                $plot_images = PlotImage::create([
                    'plot_id' => $request->id,
                    'pictures' => $pictures
                ]);
            }
        }
        $plot->plot_id = $request->plot_id;
        $plot->housing_scheme_id = $request->housingscheme_id;
        $plot->type = $request->type;
        $plot->block = $request->block;
        $plot->phase = $request->phase;
        $plot->width = $request->width;
        $plot->length = $request->length;
        $plot->sqrft = $request->sqrft;
        $plot->sqrmt = $request->sqrmt;
        $plot->marla = $request->marla;
        $plot->cost = $request->cost;
        $plot->totalcost = $request->plotcost;
        $plot->khewat_no = $request->khewat_no;
        $plot->khasra_no = $request->khasra_no;
        $plot->status = $request->status;
        $plot->location = $request->location;
        $plot->address = $request->address;
        $plot->create_by = auth()->user()->id;
        $plot->save();
        return redirect('/plot')->with(['update' => 'Plot is successfully updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Plot  $plot
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $plot_img = PlotImage::where('plot_id', $id)->delete();
        $plot = Plot::find($id)->delete();
        return back()->with(['delete' => 'Plot is successfully Delete']);
    }
}

resources/views/crm/plot/create-plot.blade.php
@extends('crm.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header">
        <h3 class="card-title">
            New Plot
        </h3>
    </div>
    <!--begin::Form-->
    <form method="POST" action="{{ route('plot.store') }}" enctype="multipart/form-data">
        @csrf

        <div class="card-body">

            <div class="form-group row">
                <label class="col-2 col-form-label">Plot Id</label>
                <div class="col-10">
                    <input class="form-control" type="text" name="plot_id" id="example-text-input" placeholder="Enter plot id"/>
                </div>
            </div>

            <div class="form-group row">
                @hasrole('admin')
                    <label class="col-2 col-form-label">Housing Scheme<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                        <div class="col-10">
                            <select class="form-control" name="housingscheme_id" id="example-text-input" required>
                                <option value="">Please Select Housing Scheme</option>
                                @foreach ($plot as $data)
                                    <option value="{{ $data->id }}">{{$data->name}}</option>
                                @endforeach
                            </select>
                        </div>
                @else
                    <label class="col-2 col-form-label">Housing Scheme<span class="text-danger font-weight-bolder font-size-lg">*</span></label>
                        <div class="col-10">
                            <input class="form-control" type="text" name="scheme_name" value="{{ $plot[0]->name ?? '' }}"  readonly/>
                            <input class="form-control" type="hidden" name="housingscheme_id" value="{{ $plot[0]->id ?? '' }}"/>
                        </div>
                @endhasrole
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label">Plot Type<span class="text-danger font-weight-bolder">*</span></label>
                <div class="col-10">
                    <select class="form-control" id="exampleSelect1" name="type" required>
                        <option value="">Select Plot Type</option>
                        <option value="Commercial">Commercial</option>
                        <option value="Residential">Residential</option>
                        <option value="Renteral">Renteral</option>
                        <option value="Villa">Villa</option>
                        <option value="House">House</option>
                    </select>
                </div>
            </div>


            <div class="form-group row">
                <label class="col-2 col-form-label">Block<span class="text-danger font-weight-bolder">*</span></label>
                <div class="col-10">
                    <select class="form-control" name="block" required>
                        <option value="">Select Block of Plot</option>
                        @foreach ($plot as $block)
                            @foreach ($block->location('block')->get() as $location)
                                <option value="{{$location->text}}">{{ $location->text }}</option>
                            @endforeach
                        @endforeach
                    </select>
                </div>
            </div>


            <div class="form-group row">
                <label class="col-2 col-form-label">Phase<span class="text-danger font-weight-bolder">*</span></label>
                <div class="col-10">
                    <select class="form-control" name="phase" required>
                        <option value="">Select Phase of Plot</option>
                        @foreach ($plot as $block)
                            @foreach ($block->location('phase')->get() as $location)
                                <option value="{{$location->text}}">{{ $location->text }}</option>
                            @endforeach
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Size<span class="text-danger font-weight-bolder">*</span></label>
                <div class="col-2">
                    <input class="form-control width" type="number" name="width" step="any" id="example-number-input" placeholder="Enter width" required/>
                </div>
                <div class="col-2">
                    <input class="form-control length" type="number" name="length" step="any" id="example-number-input" placeholder="Enter length" required/>
                </div>
                <div class="col-3">
                    <input class="form-control sqrft" type="number" name="sqrft" id="example-number-input" placeholder="Sqr ft" autocomplete="off"/>
                </div>

                <div class="col-3">
                    <input class="form-control sqrmt" type="number" name="sqrmt" id="example-number-input" placeholder="Sqr mt" autocomplete="off"/>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Cost<span class="text-danger font-weight-bolder">*</span></label>
                <div class="col-3">
                    <input class="form-control marla" type="number" name="marla" step="any" id="example-text-input" placeholder="Enter marla" required/>
                </div>
                <div class="col-3">
                    <input class="form-control cost" type="number" name="cost" step="any" id="example-text-input" placeholder="Enter cost per marla" required/>
                </div>
                <div class="col-4">
                    <input class="form-control plotcost" type="number" name="plotcost" id="example-text-input" placeholder="Plot Cost" autocomplete="off"/>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Khewat No</label>
                <div class="col-10">
                    <input class="form-control" type="text" name="khewat_no" id="example-number-input" placeholder="Enter khewat number"/>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Khasra No.</label>
                <div class="col-10">
                    <input class="form-control" type="text" name="khasra_no" id="example-number-input" placeholder="Enter khasra number"/>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label">Status<span class="text-danger font-weight-bolder">*</span></label>
                <div class="col-10">
                    <select class="form-control" id="exampleSelect1" name="status" required>
                        <option value="">Select Status</option>
                        <option value="booked">Booked</option>
                        <option value="Unbooked/Available">Unbooked/Available</option>
                        <option value="Blocked">Blocked</option>
                        <option value="Mortgage">Mortgage</option>
                        <option value="Mortgage">Mortgage</option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label">Location <span class="text-danger font-weight-bolder">*</span></label>
                <div class="col-10">
                    <select class="form-control" id="exampleSelect1" name="location" required>
                        <option value="">Select location of Plot</option>
                        <option value="main boleward">Main Boleward </option>
                        <option value="main road">Main Road</option>
                        <option value="park facing">Park Facing</option>
                        <option value="corner">Corner</option>
                        <option value="bublick building facing">Bublick Building Facing</option>
                        @foreach ($plot as $block)
                            @foreach ($block->location('location')->get() as $location)
                                <option value="{{$location->text}}">{{ $location->text }}</option>
                            @endforeach
                        @endforeach
                    </select>
                </div>
            </div>


            <div class="form-group row">
                <label class="col-2 col-form-label">Address</label>
                <div class="col-10">
                    <textarea class="form-control" type="address" name="address" id="example-text-input" rows="5">
                    </textarea>
                </div>
            </div>

            <div class="form-group row">
                <label for="example-search-input" class="col-2 col-form-label">Pictures</label>
                <div class="col-10">
                    <input type="file" class="dropify" name="plotpictures[]" data-height="200" data-allowed-file-extensions="png jpg jpeg" data-errors-position="outside"  data-max-file-size-preview="2M"  data-show-errors="true" multiple/>
                </div>
            </div>

        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-2">
                    <button type="submit" class="btn btn-success btn-lg btn-block">Save</button>
                </div>
                <div class="col-10">
                </div>
            </div>
        </div>
    </form>
</div>
@endsection
@section('footer.script')
<script>
// For Size Calculate
$('.width , .length').change(function(){
    var width = parseFloat($('.width').val()) || 0;
    var length = parseFloat($('.length').val()) || 0;
    var sqft = width * length;
    var ft = sqft.toFixed(2);
    $('.sqrft').val(ft);
    var sqmt = ft / 10.764;
    var mt = sqmt.toFixed(2);
    $('.sqrmt').val(mt);
    $( ".sqrft , .sqrmt" ).attr( "readonly", true );
});

// For Plot Cost
$('.marla, .cost').change(function(){
    var rate = parseFloat($('.marla').val()) || 0;
    var box = parseFloat($('.cost').val()) || 0;
    var totalcost = rate * box;
    $('.plotcost').val(totalcost);
    $( ".plotcost" ).attr( "readonly", true );
    console.log(totalcost);
});

</script>
@endsection

resources/views/crm/plot/plot.blade.php
@extends('crm.layouts.app')
@section('content')
<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">Plots
        </div>
        <div class="card-toolbar">
            <!--begin::Button-->
            <a href="{{ route('plot.create') }}" class="btn btn-primary font-weight-bolder">
                <span class="svg-icon svg-icon-md">
                    <i class="fa fa-plus-circle"></i>
                </span>New Record</a>
            <!--end::Button-->
        </div>
    </div>
    <div class="card-body">
        <!--begin: Search Form-->
        <!--begin::Search Form-->
        <div class="mb-7">
            <div class="row align-items-center">
                <div class="col-lg-3">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="input-icon">
                                <input type="text" class="form-control" placeholder="Search..."
                                    id="kt_datatable_search_query" />
                                <span>
                                    <i class="flaticon2-search-1 text-muted"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-xl-4 mt-5 mt-lg-0">
                    <a href="#" class="btn btn-light-primary px-6 font-weight-bold">Search</a>
                </div>
            </div>
        </div>
        <!--end::Search Form-->
        <!--end: Search Form-->
        <!--begin: Datatable-->
        <div class="panel panel-default">
            @if (session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
            @elseif (session('delete'))
                <div class="alert alert-danger">{{ session('delete') }}</div>
            @elseif (session('update'))
                <div class="alert alert-success">{{ session('update') }}</div>
            @endif
        </div>
        <table class="datatable datatable-bordered datatable-head-custom" id="kt_datatable">
            <thead>
                <tr>
                    <th >Sr No</th>
                    <th >Plot Id</th>
                    <th >Housing Scheme</th>
                    <th >Plot Type</th>
                    <th >Cost</th>
                    <th >Action</th>
                </tr>
            </thead>
            <tbody>

                <?php $x = 0 ?>
                @foreach ($plot_detials as $item)
                <tr>
                    <td>{{ $x+1 }}</td>
                    <td>{{ $item->plot_id ?? 'Not Assigned'  }}</td>
                    <td>{{ $item->housing->name}}</td>
                    <td class="text-right">{{ $item->type }}</td>
                    <td class="text-right">Rs {{ $item->totalcost }}</td>
                    <td data-field="Actions" data-autohide-disabled="false" aria-label="null" class="datatable-cell">
                        <span style="overflow: visible; position: relative; width: 125px;">
                            <a href="{{ route('plot.show',$item->id) }}" class="btn btn-sm btn-clean btn-icon mr-2" title="View details">
                                <span class="svg-icon svg-icon-md">
                                    <i class="fas fa-eye"></i>
                                </span>
                            </a>
                            <a href="{{ route('plot.edit',$item->id) }}" class="btn btn-sm btn-clean btn-icon mr-2" title="Edit details">
                                <span class="svg-icon svg-icon-md">
                                    <i class="fas fa-pen"></i>
                                </span>
                            </a>
                            <form method="Post" action="{{ route('plot.destroy',$item->id) }}" style="display: -webkit-inline-box;">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-clean btn-icon" title="Delete">
                                    <span class="svg-icon svg-icon-md">
                                        <i class="fas fa-trash"></i>
                                    </span>
                                </button>
                            </form>
                        </span>
                    </td>
                </tr>
                <?php $x++ ?>
                @endforeach
            </tbody>
        </table>
        <!--end: Datatable-->
    </div>
</div>
@endsection